services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_service
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API & Web UI port
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__API_KEY: "secret"
