version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GAME_DATA_DIR=/home/bun/app/games/
      - AXIOM_TOKEN=${AXIOM_TOKEN}
      - AXIOM_ORG_ID=${AXIOM_ORG_ID}
    volumes:
      - /var/gamedata:/home/bun/app/games/
