version: "3"

services:
  web:
    build: .
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 2s
    ports:
      - "3000:3000"
    environment:
      - GAME_DATA_DIR=/home/bun/app/assets/games/
      - AXIOM_TOKEN=${AXIOM_TOKEN}
      - AXIOM_ORG_ID=${AXIOM_ORG_ID}
    volumes:
      - /var/gamedata:/home/bun/app/assets/games/
  cache:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /var/dockerdata:/data
